I made some changes to my html and css
oluwajuwon8/My-Portfolio pull request #1
Opened 2021-09-15 16:13 UTC by oluwajuwon8

I will love to hear from you as I have done all the necessary adjustments.

2021-09-15 16:18 UTC, SajjadAhmad14 requested changes
```markdown
Hi Azeezat Omolola, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has failing linter checks on PR. Please fix all the errors. Moreover please use all the files from [this](https://github.com/microverseinc/linters-config/tree/master/html-css) linter config.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

Invalid Code Review Request **does not count** into the code reviews limit._
```

2021-09-15 17:47 UTC, DanteAlonsoHT requested changes
<h1> Status: Required Changes 🚫 </h1>

Hi @oluwajuwon8,


### You must use one of the Figma designs provided by Microverse for this and the rest of the projects about the portfolio, Take into consideration all the changes required in your design using [the Figma designs provided by Microverse](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Use the font and colors (background and font) defined for the template in Figma you selected
- The button (if the template has one) is a link `a` or `button` tag, and follow the button styling: Active, Hover, and Pressed (see design)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-15 17:47 UTC, DanteAlonsoHT commented on README.md
> +>Mobile version skeleton
- [ ] You should add a better description, just try to explain what you did, what is the main scope, what kind of technologies or techniques you used, and so on. (Add like 3 lines or more at least in your description 😉).

2021-09-15 17:47 UTC, DanteAlonsoHT commented on index.html
> +</nav>
- [ ] Your nav should be inside the `header` tag, according to the project requirements. Please, add it.

Example:
```
<header>
  <nav>
     ...
  </nav>
</header>
```

2021-09-15 17:47 UTC, DanteAlonsoHT commented on index.html
> +</html>
I liked your design, but for this and the rest of the projects about your portfolio, you should use one of 5 templates provided by Microverse, you can check [these designs in Figma]

- [ ] Use a Figma design provided by Microverse instead of your current design. Remember you should start with the mobile design.

(https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)

![image](https://user-images.githubusercontent.com/60164239/133482314-7fa51ced-cc2a-4d1f-a586-14949763c3ed.png)

2021-09-15 17:47 UTC, DanteAlonsoHT commented on index.html
> +    <h2 class="Logo"> Portfo<span>lio</span></h2>
- [ ] The logo (if the design has one) is on the left and has `a` link (`a` tag) Like the next sample:
```
<a href="#"><h2 class="Logo"> Portfo<span>lio</span></h2></a>
```

2021-09-15 17:47 UTC, DanteAlonsoHT commented on index.html
> +</div>
Your social media links should be a list using `ul` tag with `li` elements, like the next example:
```
<ul>
  <li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
  ....
</ul>
```

2021-09-16 11:09 UTC, AshakaE approved these changes
### Hi @oluwajuwon8  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 11:17 UTC, merged